-- ============================================================
--  PostgreSQL "chatbot" database schema (semantic / RAG store)
--  Matches the live table definitions. Run against PG_DB (default: chatbot).
--  Requires pgvector. BGE-M3 produces 1024-dim embeddings.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS vector;

-- ---------- RAG corpus ----------
CREATE TABLE IF NOT EXISTS hr_documents (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id    INTEGER,
    source_file VARCHAR(500),
    content     TEXT,
    embedding   vector(1024),
    created_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS hr_faq (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question    TEXT,
    answer      TEXT,
    embedding   vector(1024),
    created_at  TIMESTAMP DEFAULT now()
);

-- ---------- SQL-agent knowledge ----------
CREATE TABLE IF NOT EXISTS schema_tables (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name           TEXT,
    schema_chunk         TEXT,   -- DDL / column listing
    enriched_description TEXT,   -- NL description of the table + when to use it
    embedding            vector(1024),
    created_at           TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS schema_domains (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_name TEXT,
    description TEXT,
    embedding   vector(1024),
    created_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sql_examples (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question    TEXT,
    sql_query   TEXT,
    tables_used TEXT,
    embedding   vector(1024),
    created_at  TIMESTAMP DEFAULT now()
);

-- ---------- ANN indexes (cosine) ----------
CREATE INDEX IF NOT EXISTS hr_documents_emb_idx
    ON hr_documents USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX IF NOT EXISTS hr_faq_emb_idx
    ON hr_faq USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX IF NOT EXISTS schema_tables_emb_idx
    ON schema_tables USING ivfflat (embedding vector_cosine_ops) WITH (lists = 50);
CREATE INDEX IF NOT EXISTS schema_domains_emb_idx
    ON schema_domains USING ivfflat (embedding vector_cosine_ops) WITH (lists = 50);
CREATE INDEX IF NOT EXISTS sql_examples_emb_idx
    ON sql_examples USING ivfflat (embedding vector_cosine_ops) WITH (lists = 50);

-- ============================================================
--  Seed: describe the allow-listed hrms (SQL Server) tables so the SQL agent
--  can map natural language to the correct tables/columns.
--  Run scripts/embed_backfill.py afterwards to populate the `embedding` column.
-- ============================================================

INSERT INTO schema_tables (table_name, enriched_description, schema_chunk) VALUES
('employees',
 'Master record of each employee with identity and personal details. Use this '
 'table for an employee''s name, date of birth, gender, marital status, blood '
 'group, nationality, statutory identifiers (PAN, UAN, ESIC, Aadhaar) and '
 'employee code. The primary key Id IS the Employee ID used for login/RLS.',
 'employees(Id BIGINT PK [Employee ID], FirstName NVARCHAR, LastName NVARCHAR, '
 'DateOfBirth DATETIME, Gender INT, Nationality INT, CountryOfOrigin BIGINT, '
 'MaritalStatus INT, BloodGroup INT, Status INT, Code NVARCHAR, '
 'ClientEmployeeCode NVARCHAR, PAN NVARCHAR, UAN NVARCHAR, ESIC NVARCHAR, '
 'Aadhaar NVARCHAR, FatherName NVARCHAR, Religion BIGINT, MarriageDate DATETIME, '
 'IsDifferentlyabled BIT, DisabilityPercentage DECIMAL, CreatedOn DATETIME)'),
('EmployeeEmployment',
 'Employment record for an employee: joining/start date, employment status and '
 'type, designation, department, grade, work location, reporting manager, '
 'confirmation date, resignation/last working day and notice period. Join to '
 'employees on EmployeeEmployment.EmployeeId = employees.Id.',
 'EmployeeEmployment(Id BIGINT PK, EmployeeId BIGINT FK->employees.Id, '
 'StartDate DATETIME [joining date], EndDate DATETIME, Status INT, '
 'Designation NVARCHAR, Department NVARCHAR, Grade NVARCHAR, WorkLocation NVARCHAR, '
 'ManagerId BIGINT, EmploymentType INT, IsResigned BIT, ResignationDate DATETIME, '
 'LWD DATETIME [last working day], NoticePeriodDays DECIMAL, '
 'DateOfConfirmation DATETIME, JobProfile NVARCHAR, CompanyId BIGINT, '
 'ClientId BIGINT, TeamId BIGINT)');

INSERT INTO schema_domains (domain_name, description) VALUES
('Employee Directory',
 'Who works here: names, personal details, statutory IDs and employee codes. '
 'Backed by the employees table.'),
('Employment & Onboarding',
 'Joining dates, employment type/status, designation, department, grade, '
 'reporting manager, confirmation, resignation and notice period. Backed by '
 'the EmployeeEmployment table.');
